// Copyright (c) Privasys. All rights reserved.
// Licensed under the Apache License, Version 2.0.

package vtt

import (
	"strings"
	"testing"
	"time"
)

// A Teams transcript: voice tags, an identifier per cue, a note block and a
// styled span inside a cue.
const teamsFixture = "\xef\xbb\xbfWEBVTT\r\n\r\nNOTE generated by a fake\r\n\r\n" +
	"1\r\n00:00:01.000 --> 00:00:03.500\r\n<v Alice Smith>Good morning everyone.</v>\r\n\r\n" +
	"2\r\n00:00:03.600 --> 00:00:05.000\r\n<v Alice Smith>Shall we <b>start</b>?</v>\r\n\r\n" +
	"3\r\n00:00:05.100 --> 00:00:07.000\r\n<v Bob Jones>Yes, let&#39;s go &amp; begin.</v>\r\n\r\n" +
	"4\r\n00:00:07.100 --> 00:00:09.000\r\n<v Alice Smith>The agenda is short.</v>\r\n"

// A Zoom transcript: the speaker as a prefix, no identifiers on some cues,
// a comma decimal separator, and a line with a colon that is not a name.
const zoomFixture = `WEBVTT

1
00:00:00.599 --> 00:00:03.900
Carol: Welcome to the weekly sync

00:00:04.000 --> 00:00:06,500
Carol: Item one: the release

00:00:06.600 --> 00:00:08.000
Dan: https://example.org: not a speaker

00:00:08.100 --> 01:02:03.400
Dan: We ship on Thursday
`

func TestTeamsVoiceTags(t *testing.T) {
	tr, err := Parse(strings.NewReader(teamsFixture))
	if err != nil {
		t.Fatal(err)
	}
	if len(tr.Cues) != 4 {
		t.Fatalf("cues: %d", len(tr.Cues))
	}
	if tr.Cues[0].ID != "1" || tr.Cues[0].Speaker != "Alice Smith" || tr.Cues[0].Text != "Good morning everyone." {
		t.Errorf("cue 1: %+v", tr.Cues[0])
	}
	if tr.Cues[1].Text != "Shall we start?" {
		t.Errorf("inner tags are stripped: %q", tr.Cues[1].Text)
	}
	if tr.Cues[2].Speaker != "Bob Jones" || !strings.Contains(tr.Cues[2].Text, "& begin") {
		t.Errorf("entities: %+v", tr.Cues[2])
	}
	if got := tr.Speakers(); len(got) != 2 || got[0] != "Alice Smith" || got[1] != "Bob Jones" {
		t.Errorf("speakers: %v", got)
	}
	text := tr.Text()
	want := "[00:00:01] Alice Smith: Good morning everyone. Shall we start?\n" +
		"[00:00:05] Bob Jones: Yes, let&#39;s go & begin.\n" +
		"[00:00:07] Alice Smith: The agenda is short.\n"
	if text != want {
		t.Errorf("text:\n%s\nwant:\n%s", text, want)
	}
	if tr.Duration() != 9*time.Second {
		t.Errorf("duration: %v", tr.Duration())
	}
}

func TestZoomPrefixes(t *testing.T) {
	tr, err := Parse(strings.NewReader(zoomFixture))
	if err != nil {
		t.Fatal(err)
	}
	if len(tr.Cues) != 4 {
		t.Fatalf("cues: %d", len(tr.Cues))
	}
	if tr.Cues[0].Speaker != "Carol" || tr.Cues[0].Text != "Welcome to the weekly sync" {
		t.Errorf("cue 1: %+v", tr.Cues[0])
	}
	// The shortest prefix wins, so the second colon stays in the text.
	if tr.Cues[1].Speaker != "Carol" || tr.Cues[1].Text != "Item one: the release" {
		t.Errorf("cue 2: %+v", tr.Cues[1])
	}
	if tr.Cues[1].End != 6500*time.Millisecond {
		t.Errorf("comma decimal: %v", tr.Cues[1].End)
	}
	if tr.Cues[2].Speaker != "Dan" {
		t.Errorf("cue 3: %+v", tr.Cues[2])
	}
	if tr.Cues[3].End != time.Hour+2*time.Minute+3400*time.Millisecond {
		t.Errorf("hours: %v", tr.Cues[3].End)
	}
	paras := tr.Paragraphs()
	if len(paras) != 2 || paras[1].Speaker != "Dan" {
		t.Errorf("paragraphs: %+v", paras)
	}
	if !strings.HasPrefix(tr.Text(), "[00:00:01] Carol: Welcome") {
		t.Errorf("text: %q", tr.Text())
	}
}

func TestUnattributedLinesStayUnattributed(t *testing.T) {
	src := "WEBVTT\n\n00:00.000 --> 00:01.000\n<v A>one</v>\n\n00:01.000 --> 00:02.000\ntwo\n\n00:02.000 --> 00:03.000\nthree\n"
	tr, err := Parse(strings.NewReader(src))
	if err != nil {
		t.Fatal(err)
	}
	paras := tr.Paragraphs()
	if len(paras) != 2 || paras[1].Speaker != "" || paras[1].Text != "two three" {
		t.Errorf("paragraphs: %+v", paras)
	}
	if !strings.Contains(tr.Text(), "[00:00:01] two three") {
		t.Errorf("text: %q", tr.Text())
	}
}

func TestNotVTT(t *testing.T) {
	if _, err := Parse(strings.NewReader("hello")); err != ErrNotVTT {
		t.Errorf("err: %v", err)
	}
	tr, err := Parse(strings.NewReader("WEBVTT\n"))
	if err != nil || len(tr.Cues) != 0 || tr.Text() != "" {
		t.Errorf("empty: %v %+v", err, tr)
	}
}
